server:
  http2:
    enabled: true
  servlet:
    jsp:
      registered: false
  compression:
    enabled: true
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  data:
    mongodb:
      auto-index-creation: true
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true

gw2:
  api:
    version: 2021-07-24T00:00:00Z

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
        - metrics
        - loggers
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
