apiVersion: v1
kind: Secret
metadata:
  name: gw2e-lottery-secret
  namespace: gw2e-lottery
type: Opaque
data:
  mongodb-uri: "mongodb+srv://<username>:<password>@mongodb-svc.mongodb.svc.cluster.local"
