apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw2e-lottery
  namespace: gw2e-lottery
  labels:
    app.kubernetes.io/name: gw2e-lottery
    app.kubernetes.io/component: gw2e-lottery
    app.kubernetes.io/version: 1.1.5
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gw2e-lottery
      app.kubernetes.io/component: gw2e-lottery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gw2e-lottery
        app.kubernetes.io/component: gw2e-lottery
        app.kubernetes.io/version: 1.1.5
    spec:
      containers:
      - name: gw2e-lottery
        image: ghcr.io/gbaso/gw2e-lottery:1.1.5
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-uri
---
apiVersion: v1
kind: Service
metadata:
  name: gw2e-lottery
  namespace: gw2e-lottery
  labels:
    app.kubernetes.io/name: gw2e-lottery
    app.kubernetes.io/component: gw2e-lottery
spec:
  selector:
    app.kubernetes.io/name: gw2e-lottery
    app.kubernetes.io/component: gw2e-lottery
  ports:
  - port: 8080
    targetPort: 8080
