volumes:
  mongodata: {}

services:
  lottery:
    image: ghcr.io/gbaso/gw2e-lottery
    container_name: gw2e-lottery
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: gw2e_lottery
    ports:
    - "8081:8080"
    restart: unless-stopped
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
