name: Build docker image

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: ./mvnw -B install
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v3.0.3
      - name: Build and Publish Image
        run: ./mvnw -B spring-boot:build-image -Pnative -Dspring-boot.build-image.publish=true -Ddocker.publishRegistry.username=${{ github.actor }} -Ddocker.publishRegistry.password=${{ secrets.GITHUB_TOKEN }}
